# Generated by Django 4.1 on 2023-09-25 06:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imgid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.images'),
        ),
        migrations.AddField(
            model_name='superdeal',
            name='imgid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.images'),
        ),
    ]
