# Generated by Django 4.1 on 2023-09-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_category_imgid_superdeal_imgid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='superdeal',
            old_name='discount_price',
            new_name='discount',
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
