# Generated by Django 4.1 on 2023-09-25 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_remove_customer_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='colorid',
            field=models.ManyToManyField(to='ecommerce.colors'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 20, 17, 43, 618703)),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 25, 20, 17, 43, 619699)),
        ),
    ]
