# Generated by Django 4.1 on 2023-09-25 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_remove_customer_created_at_remove_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrating',
            name='rating',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
            preserve_default=False,
        ),
    ]
