# Generated by Django 4.1 on 2023-09-25 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_reviewrating_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviewrating',
            name='avg_rating',
        ),
        migrations.AddField(
            model_name='product',
            name='avg_rating',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
