# Generated by Django 4.1 on 2023-09-27 07:56

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_remove_reviewrating_avg_rating_product_avg_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='isowner',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='customer',
            name='username',
            field=models.CharField(max_length=40),
        ),
        migrations.CreateModel(
            name='PasswordResetCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(default=0, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.customer')),
            ],
        ),
    ]
