# Generated by Django 4.1 on 2023-10-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_customer_isowner_alter_customer_telephone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='created_at',
            new_name='shipped_at',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
