# Generated by Django 4.1 on 2023-10-06 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0014_customer_gender_customer_imgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='ecommerce.attributes'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.CharField(default='This is a product description', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
