# Generated by Django 4.1 on 2023-10-07 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0015_product_attribution_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='address',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='latitude',
            field=models.DecimalField(decimal_places=9, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='longitude',
            field=models.DecimalField(decimal_places=9, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='colorid',
            field=models.ManyToManyField(blank=True, null=True, to='ecommerce.colors'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='imgid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.images'),
        ),
    ]
