# Generated by Django 4.1 on 2023-10-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0016_orderdetail_address_alter_address_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='description',
            field=models.CharField(default='Current Location', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=55),
        ),
    ]
