# Generated by Django 4.1 on 2023-10-10 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_order_alter_orderdetail_amount_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderProduct',
        ),
    ]
