# Generated by Django 4.1 on 2023-10-10 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0020_colors_imgid_remove_attributes_size_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='imgid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.images'),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='imgid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.images'),
        ),
    ]
