# Generated by Django 4.1 on 2023-10-10 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0021_alter_colors_imgid_alter_sizes_imgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='imgid',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.images'),
        ),
        migrations.AlterField(
            model_name='sizes',
            name='imgid',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.images'),
        ),
    ]
