# Generated by Django 4.1 on 2023-10-10 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0022_alter_colors_imgid_alter_sizes_imgid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colors',
            name='imgid',
        ),
        migrations.RemoveField(
            model_name='sizes',
            name='imgid',
        ),
    ]
