# Generated by Django 4.1 on 2023-10-10 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0023_remove_colors_imgid_remove_sizes_imgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, default='Male', max_length=10, null=True),
        ),
    ]
