# Generated by Django 4.1 on 2023-10-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0025_remove_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
