# Generated by Django 4.1 on 2023-10-10 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0027_remove_customer_gender_colors_imgid_sizes_imgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gen',
            field=models.CharField(default=None, max_length=25),
            preserve_default=False,
        ),
    ]
