# Generated by Django 4.1 on 2023-10-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0028_customer_gen'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(blank=True, default='Cambodia', max_length=255, null=True),
        ),
    ]
