# Generated by Django 4.1 on 2023-10-10 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0029_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='imgid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.images'),
        ),
    ]
