# Generated by Django 4.1 on 2023-10-10 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0030_alter_category_imgid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='gen',
            new_name='gender',
        ),
        migrations.RemoveField(
            model_name='colors',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='sizes',
            name='imgid',
        ),
        migrations.AlterField(
            model_name='product',
            name='avg_rating',
            field=models.FloatField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
