# Generated by Django 4.1 on 2023-10-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0036_alter_address_latitude_alter_address_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isfavorite',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
