# Generated by Django 4.1 on 2023-10-29 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0037_product_isfavorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='isfavorite',
        ),
    ]
