# Generated by Django 4.1 on 2023-10-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0038_remove_product_isfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='superdeal',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
