# Generated by Django 4.1 on 2023-10-31 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0039_superdeal_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='superdeal',
            name='product',
        ),
        migrations.AddField(
            model_name='superdeal',
            name='product',
            field=models.ManyToManyField(to='ecommerce.product'),
        ),
    ]
