# Generated by Django 4.1 on 2023-11-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0040_remove_superdeal_product_superdeal_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='unit',
            field=models.CharField(blank=True, default='kg', max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='colors',
            name='code',
            field=models.CharField(blank=True, default='#EEEEEE', max_length=10, null=True),
        ),
    ]
