# Generated by Django 4.1 on 2023-11-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0042_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='imgid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.images'),
        ),
        migrations.AlterField(
            model_name='images',
            name='images',
            field=models.ImageField(default=None, error_messages='image cannot be empty', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='ecommerce.customer'),
        ),
    ]
