# Generated by Django 4.1 on 2023-11-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0043_attributes_price_alter_customer_imgid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='price',
        ),
        migrations.AddField(
            model_name='colors',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
