# Generated by Django 4.1 on 2023-11-15 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0045_colors_stockqty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='imgid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecommerce.images'),
        ),
    ]
