# Generated by Django 4.1 on 2023-11-18 13:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0047_alter_customer_imgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 18, 20, 50, 12, 327998)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='imgid',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecommerce.images'),
        ),
    ]
