# Generated by Django 4.1 on 2023-11-29 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0049_alter_customer_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 15, 41, 15, 746696)),
        ),
    ]
