# Generated by Django 4.1 on 2023-11-29 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0050_alter_customer_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 29, 16, 16, 19, 13354)),
        ),
    ]
